//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class IndexCSP:public drogon::DrTemplate<void>
{
public:
    IndexCSP(){};
	virtual ~IndexCSP(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
